eureka:
  instance:
    prefer-ip-address: true  # Use IP address instead of hostname for registration
  client:
    register-with-eureka: true  # Ensures the gateway registers with Eureka
    fetch-registry: true        # Fetch registry information from Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/
